### ISSUE TITLE
Where is train.list?

### ISSUE THREAD

**Issue by JuiceLemonLemon** [On-Point-RND/QuantNAS#1]
Hello, thank you for sharing your great work.
I have a problem when I run you code.

FileNotFoundError: [Errno 2] No such file or directory: '/***/DIV2K/processed_200_st70/HR/train.list'

**Comment by diff7** [comment]
Hi,

There is a chance we added this script manually later on. The files `train.list` and `val.list` contain file names within the corresponding folders. I do not remember why we did it, but it should be correct.

After you run `make_set.py`, you can create these files manually. Sorry for the inconvenience.

Let me know if that does not work, and I will try to find the script.
